apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: default
type: Opaque
stringData:
  DEBUG: "True"
  SECRET_KEY: "your-super-secret-key"
  DB_NAME: "django"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
