name: Django CI - SonarQube, Trivy & GitLeaks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Trivy Installation
      run: |
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy

    - name: Trivy FS Scan
      run: trivy fs --format table -o fs-report.json .

    - name: Gitleaks Installation
      run: sudo apt install gitleaks -y
    - name: Gitleaks Code Scan
      run: gitleaks detect source . -r gitleaks-report.json -f json

  docker-build-push:
    runs-on: ubuntu-latest
    needs: security-check

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker tag
      id: version
      run: |
        VERSION=v$(date +"%Y%m%d%H%M%S")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # - name: Build Docker Image
    #   run: |
    #     docker build . -t vigneshvicky97/django-todo:${{ env.VERSION }} 

    # - name: Push Docker Image
    #   run: |
    #     docker push vigneshvicky97/django-todo:${{ env.VERSION }}


    - name: Build and Push Multi-Platform Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: vigneshvicky97/django-todo:${{ env.VERSION }} 
        platforms: linux/amd64,linux/arm64

    - name: Update K8s Manifests
      run: |
        cat k8s/django-deployment.yaml
        sed -i "s|vigneshvicky97/django-todo:[^[:space:]]*|vigneshvicky97/django-todo:${{ env.VERSION }}|g" k8s/django-deployment.yaml
        cat k8s/django-deployment.yaml


    - name: Commit the changes
      run: |
        git config --global user.email "<>"
        git config --global user.name "GitHub Actions Bot"
        git add k8s/django-deployment.yaml
        git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
        git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/vigneshs-dev/DevSecOps-Projects-Own/todo_project.git
        git push origin main


